### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by mathiasbynens** [abozhilov/regexter.com#2]
Allow permalinking to a given test case by adding the regex, flag settings, and test data to the URL hash.

E.g. something like `http://regexter.com/#re=%5Ba-z%5D*&flags=igm&data=foo%0Abar`  would use `[a-z]*` for the regular expression, all three flags (case insensitive, global, and multiline) and have the following test data:

```
foo
bar
```

**Comment by abozhilov** [comment]
It is good idea, I thought about it, but didn't have enough time. 
Also looking for feedback are the results OK for you.
